package com.yang.Model;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_COMMENT.ID
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_COMMENT.PARENT_ID
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_COMMENT.TYPE
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_COMMENT.COMMENTATOR
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    private Integer commentator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_COMMENT.GMT_CREATE
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_COMMENT.GMT_MODIFIED
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_COMMENT.LIKE_COUNT
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    private Long likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_COMMENT.CONTENT
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_COMMENT.ID
     *
     * @return the value of TB_COMMENT.ID
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_COMMENT.ID
     *
     * @param id the value for TB_COMMENT.ID
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_COMMENT.PARENT_ID
     *
     * @return the value of TB_COMMENT.PARENT_ID
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_COMMENT.PARENT_ID
     *
     * @param parentId the value for TB_COMMENT.PARENT_ID
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_COMMENT.TYPE
     *
     * @return the value of TB_COMMENT.TYPE
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_COMMENT.TYPE
     *
     * @param type the value for TB_COMMENT.TYPE
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_COMMENT.COMMENTATOR
     *
     * @return the value of TB_COMMENT.COMMENTATOR
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    public Integer getCommentator() {
        return commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_COMMENT.COMMENTATOR
     *
     * @param commentator the value for TB_COMMENT.COMMENTATOR
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    public void setCommentator(Integer commentator) {
        this.commentator = commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_COMMENT.GMT_CREATE
     *
     * @return the value of TB_COMMENT.GMT_CREATE
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_COMMENT.GMT_CREATE
     *
     * @param gmtCreate the value for TB_COMMENT.GMT_CREATE
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_COMMENT.GMT_MODIFIED
     *
     * @return the value of TB_COMMENT.GMT_MODIFIED
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_COMMENT.GMT_MODIFIED
     *
     * @param gmtModified the value for TB_COMMENT.GMT_MODIFIED
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_COMMENT.LIKE_COUNT
     *
     * @return the value of TB_COMMENT.LIKE_COUNT
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    public Long getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_COMMENT.LIKE_COUNT
     *
     * @param likeCount the value for TB_COMMENT.LIKE_COUNT
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    public void setLikeCount(Long likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_COMMENT.CONTENT
     *
     * @return the value of TB_COMMENT.CONTENT
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_COMMENT.CONTENT
     *
     * @param content the value for TB_COMMENT.CONTENT
     *
     * @mbg.generated Thu Dec 15 15:44:23 GMT 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}