package com.yang.Model;

public class Notification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_NOTIFICATION.ID
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_NOTIFICATION.NOTIFIER
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    private Long notifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_NOTIFICATION.RECEIVER
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    private Long receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_NOTIFICATION.OUTERID
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    private Long outerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_NOTIFICATION.TYPE
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_NOTIFICATION.GMT_CREATE
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_NOTIFICATION.STATUS
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_NOTIFICATION.NOTIFIER_NAME
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    private String notifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_NOTIFICATION.OUTER_TITLE
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    private String outerTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_NOTIFICATION.ID
     *
     * @return the value of TB_NOTIFICATION.ID
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_NOTIFICATION.ID
     *
     * @param id the value for TB_NOTIFICATION.ID
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_NOTIFICATION.NOTIFIER
     *
     * @return the value of TB_NOTIFICATION.NOTIFIER
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    public Long getNotifier() {
        return notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_NOTIFICATION.NOTIFIER
     *
     * @param notifier the value for TB_NOTIFICATION.NOTIFIER
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    public void setNotifier(Long notifier) {
        this.notifier = notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_NOTIFICATION.RECEIVER
     *
     * @return the value of TB_NOTIFICATION.RECEIVER
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    public Long getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_NOTIFICATION.RECEIVER
     *
     * @param receiver the value for TB_NOTIFICATION.RECEIVER
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    public void setReceiver(Long receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_NOTIFICATION.OUTERID
     *
     * @return the value of TB_NOTIFICATION.OUTERID
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    public Long getOuterid() {
        return outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_NOTIFICATION.OUTERID
     *
     * @param outerid the value for TB_NOTIFICATION.OUTERID
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    public void setOuterid(Long outerid) {
        this.outerid = outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_NOTIFICATION.TYPE
     *
     * @return the value of TB_NOTIFICATION.TYPE
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_NOTIFICATION.TYPE
     *
     * @param type the value for TB_NOTIFICATION.TYPE
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_NOTIFICATION.GMT_CREATE
     *
     * @return the value of TB_NOTIFICATION.GMT_CREATE
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_NOTIFICATION.GMT_CREATE
     *
     * @param gmtCreate the value for TB_NOTIFICATION.GMT_CREATE
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_NOTIFICATION.STATUS
     *
     * @return the value of TB_NOTIFICATION.STATUS
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_NOTIFICATION.STATUS
     *
     * @param status the value for TB_NOTIFICATION.STATUS
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_NOTIFICATION.NOTIFIER_NAME
     *
     * @return the value of TB_NOTIFICATION.NOTIFIER_NAME
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    public String getNotifierName() {
        return notifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_NOTIFICATION.NOTIFIER_NAME
     *
     * @param notifierName the value for TB_NOTIFICATION.NOTIFIER_NAME
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    public void setNotifierName(String notifierName) {
        this.notifierName = notifierName == null ? null : notifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_NOTIFICATION.OUTER_TITLE
     *
     * @return the value of TB_NOTIFICATION.OUTER_TITLE
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    public String getOuterTitle() {
        return outerTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_NOTIFICATION.OUTER_TITLE
     *
     * @param outerTitle the value for TB_NOTIFICATION.OUTER_TITLE
     *
     * @mbg.generated Mon Dec 26 19:06:51 GMT 2022
     */
    public void setOuterTitle(String outerTitle) {
        this.outerTitle = outerTitle == null ? null : outerTitle.trim();
    }
}