//package com.yang.Model;
//
//import lombok.Data;
//
//import javax.persistence.criteria.CriteriaBuilder;
//
//@Data
//public class Question {
//    private Integer id;
//    private String title;
//    private String description;
//    private Long gmt_create;
//    private Long gmt_modified;
//    private Integer customer_id;
//    private Integer comment_volume;
//    private Integer read_volume;
//    private Integer like_volume;
//    private String tag;
//}

package com.yang.Model;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_QUESTION.ID
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_QUESTION.TITLE
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_QUESTION.DESCRIPTION
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_QUESTION.GMT_CREATE
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_QUESTION.GMT_MODIFIED
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_QUESTION.CUSTOMER_ID
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_QUESTION.COMMENT_VOLUME
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    private Integer commentVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_QUESTION.READ_VOLUME
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    private Integer readVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_QUESTION.LIKE_VOLUME
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    private Integer likeVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_QUESTION.TAG
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    private String tag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_QUESTION.ID
     *
     * @return the value of TB_QUESTION.ID
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_QUESTION.ID
     *
     * @param id the value for TB_QUESTION.ID
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_QUESTION.TITLE
     *
     * @return the value of TB_QUESTION.TITLE
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_QUESTION.TITLE
     *
     * @param title the value for TB_QUESTION.TITLE
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_QUESTION.DESCRIPTION
     *
     * @return the value of TB_QUESTION.DESCRIPTION
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_QUESTION.DESCRIPTION
     *
     * @param description the value for TB_QUESTION.DESCRIPTION
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_QUESTION.GMT_CREATE
     *
     * @return the value of TB_QUESTION.GMT_CREATE
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_QUESTION.GMT_CREATE
     *
     * @param gmtCreate the value for TB_QUESTION.GMT_CREATE
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_QUESTION.GMT_MODIFIED
     *
     * @return the value of TB_QUESTION.GMT_MODIFIED
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_QUESTION.GMT_MODIFIED
     *
     * @param gmtModified the value for TB_QUESTION.GMT_MODIFIED
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_QUESTION.CUSTOMER_ID
     *
     * @return the value of TB_QUESTION.CUSTOMER_ID
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_QUESTION.CUSTOMER_ID
     *
     * @param customerId the value for TB_QUESTION.CUSTOMER_ID
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_QUESTION.COMMENT_VOLUME
     *
     * @return the value of TB_QUESTION.COMMENT_VOLUME
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    public Integer getCommentVolume() {
        return commentVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_QUESTION.COMMENT_VOLUME
     *
     * @param commentVolume the value for TB_QUESTION.COMMENT_VOLUME
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    public void setCommentVolume(Integer commentVolume) {
        this.commentVolume = commentVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_QUESTION.READ_VOLUME
     *
     * @return the value of TB_QUESTION.READ_VOLUME
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    public Integer getReadVolume() {
        return readVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_QUESTION.READ_VOLUME
     *
     * @param readVolume the value for TB_QUESTION.READ_VOLUME
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    public void setReadVolume(Integer readVolume) {
        this.readVolume = readVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_QUESTION.LIKE_VOLUME
     *
     * @return the value of TB_QUESTION.LIKE_VOLUME
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    public Integer getLikeVolume() {
        return likeVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_QUESTION.LIKE_VOLUME
     *
     * @param likeVolume the value for TB_QUESTION.LIKE_VOLUME
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    public void setLikeVolume(Integer likeVolume) {
        this.likeVolume = likeVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_QUESTION.TAG
     *
     * @return the value of TB_QUESTION.TAG
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_QUESTION.TAG
     *
     * @param tag the value for TB_QUESTION.TAG
     *
     * @mbg.generated Mon Dec 12 16:50:34 GMT 2022
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }
}