package com.yang.mapper;

import com.yang.Model.Comment;
import com.yang.Model.CommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COMMENT
     *
     * @mbg.generated Mon Dec 26 19:00:31 GMT 2022
     */
    long countByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COMMENT
     *
     * @mbg.generated Mon Dec 26 19:00:31 GMT 2022
     */
    int deleteByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COMMENT
     *
     * @mbg.generated Mon Dec 26 19:00:31 GMT 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COMMENT
     *
     * @mbg.generated Mon Dec 26 19:00:31 GMT 2022
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COMMENT
     *
     * @mbg.generated Mon Dec 26 19:00:31 GMT 2022
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COMMENT
     *
     * @mbg.generated Mon Dec 26 19:00:31 GMT 2022
     */
    List<Comment> selectByExampleWithRowbounds(CommentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COMMENT
     *
     * @mbg.generated Mon Dec 26 19:00:31 GMT 2022
     */
    List<Comment> selectByExample(CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COMMENT
     *
     * @mbg.generated Mon Dec 26 19:00:31 GMT 2022
     */
    Comment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COMMENT
     *
     * @mbg.generated Mon Dec 26 19:00:31 GMT 2022
     */
    int updateByExampleSelective(@Param("record") Comment record, @Param("example") CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COMMENT
     *
     * @mbg.generated Mon Dec 26 19:00:31 GMT 2022
     */
    int updateByExample(@Param("record") Comment record, @Param("example") CommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COMMENT
     *
     * @mbg.generated Mon Dec 26 19:00:31 GMT 2022
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_COMMENT
     *
     * @mbg.generated Mon Dec 26 19:00:31 GMT 2022
     */
    int updateByPrimaryKey(Comment record);
}